config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'shows#index'

  resource :shows
  patch 'shows/edit'
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend SimpleCalendar

  has_calendar attribute: :release

  belongs_to :show

  default_scope do
    order :release
  end

  scope :upcoming, -> do
    where arel_table[:release].gteq(DateTime.now)
  end
end

app/models/show.rb
class Show < ActiveRecord::Base
  self.primary_key = 'tv_rage_id'

  has_many :upcoming_episodes,
           class_name: Event

  has_many :show_user_assignments,
           dependent: :destroy

  has_many :users,
           through: :show_user_assignments

  scope :active, -> do
    where status: ["1", "9", "10"]
  end

  scope :alphabetically, -> do
    order :name
  end

  def self.search(show_name)
    TvRage::Shows::SearchService.new(show_name).call
  end
end

app/models/show_user_assignment.rb
class ShowUserAssignment < ActiveRecord::Base
  belongs_to :show
  belongs_to :user
end

app/models/tv_rage_sync.rb
class TvRageSync < ActiveRecord::Base
  scope :shows, -> do
    where data_type: :show
  end

  scope :events, -> do
    where data_type: :event
  end

  default_scope do
    order :created_at
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :show_user_assignments,
           dependent: :destroy

  has_many :shows,
           through: :show_user_assignments

  has_many :upcoming_episodes,
           class_name: Event,
           through: :shows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  expose :upcoming_episodes do
    current_user.upcoming_episodes
  end

  def index
  end

  def edit
    current_user.update_attributes user_params

    redirect_to root_path, notice: 'Your shows were updated'
  end


  private

  def user_params
    params[:user].permit(show_ids: [])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  expose :upcoming_episodes do
    current_user.upcoming_episodes
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add(path, text)
    link_to(path, class: 'btn btn-success') do
      content_tag(:i, text, class: 'glyphicon glyphicon-plus')
    end
  end

  def link_to_edit(path, size = :sm)
    link_to(path, class: "btn-#{size} btn-warning", title: 'Editovat') do
      content_tag(:i, nil, class: 'glyphicon glyphicon-pencil')
    end
  end

  def link_to_show(path, size = :sm)
    link_to(path, class: "btn-#{size} btn-primary", title: 'Zobrazit detail') do
      content_tag(:i, nil, class: 'glyphicon glyphicon-search')
    end
  end

  def link_to_destroy(path, size = :sm)
    link_to path,
            method: :delete,
            class: "btn-#{size} btn-danger",
            title: 'Odstranit',
            data: {confirm: 'Určitě? Tato změna je nevratná.'} do

      content_tag(:i, nil, class: 'glyphicon glyphicon-trash')
    end
  end
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                               msg.html_safe, :class => "alert fade in alert-#{type} #{options[:class]}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title><%= content_for?(:title) ? yield(:title) : "TV shows calendar" %></title>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->

        <h1><%= link_to 'TV shows calendar', root_path %></h1>
        <!--
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li <%if controller_name == 'shows'%>class="active"<% end %>><%= link_to "Home", root_path %></li>
          </ul>
        </div>
      </div> -->
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-9" id="page-content">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

        <div class="col-md-3">
          <nav class="nav-sidebar navbar-fixed">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to destroy_user_session_path, :method => :delete do %><i class="glyphicon glyphicon-off"></i> Logout<% end %></li>
              <% end %>
            </ul>
          </nav>
        </div>
        <!---->
      </div><!--/row-->

      <footer>
        <p>&copy; VM <%= Date.today.strftime("%Y") %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shows/_agenda.html.haml
%h3
  Nearest episodes

%ul
  - upcoming_episodes.limit(3).each do |episode|
    %li
      = "#{episode.name} (#{episode.release.strftime('%d/%m')})"

app/views/shows/_calendar.html.haml
%h3
  Calendar overview

#calendar-overview
  = month_calendar events: upcoming_episodes do |date, upcoming_episodes|
    - if date >= Date.today
      %strong
        = date.strftime("%d/%m")

    - else
      = date.strftime("%d/%m")

    - upcoming_episodes.each do |episode|
      %div
        = episode.name

app/views/shows/_shows.html.haml
%h3
  = current_user.shows.present? ? 'My shows' : 'Step 1: find your favorite shows'

= simple_form_for current_user, url: edit_shows_path do |f|
  = f.association :shows,
                  label: false,
                  collection: Show.active.alphabetically,
                  input_html: { class: 'chosen-select' }

  = f.button :submit, 'Save', class: 'btn-primary btn-large'

app/views/shows/index.html.haml
%h2
  Upcoming episodes

- unless current_user.shows.blank?
  = render 'agenda'
  = render 'calendar'

= render 'shows'